name: Scott Fitzgerald
favicon: null
layout_spectrum: 1
typography_spectrum: 0.96492
title: Twin Cities Real Estate
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000500'
    - '#88d1e5'
    - '#6bc050'
    - '#384a35'
  brandStrength: 0.6538497030269355
  lightness: 0.7645540973171592
  saturation: 0.8654016165528446
  rhythmicContrast: 0.13727355189621449
purpose: []
